function Get-MeowskyWindowsTheme {
  param($Theme)

  Assert-MeowskyIdentityTheme -Theme $Theme -ExpectedId $Theme.id
  if ($Theme.name -match '[\x00-\x1f]' -or $Theme.name.StartsWith('@')) {
    throw 'Windows theme name must be plain text without control characters or a resource reference.'
  }
  $localData = $env:LOCALAPPDATA
  if (-not $localData) { $localData = [Environment]::GetFolderPath('LocalApplicationData') }
  if (-not $localData -or -not [IO.Path]::IsPathRooted($localData)) {
    throw 'Cannot resolve an absolute per-user LocalApplicationData directory for the Windows theme.'
  }
  $path = [IO.Path]::GetFullPath((Join-Path $localData "Microsoft/Windows/Themes/meowsky-$($Theme.id).theme"))
  # Windows system color names intentionally use Hilight, not Highlight.
  $roles = [ordered]@{
    Background = 'background'; Window = 'background'; WindowText = 'text'
    HotTrackingColor = 'accent'; GrayText = 'muted'
    HilightText = 'text'; Hilight = 'selection'
    ButtonText = 'text'; ButtonFace = 'surface'
    Menu = 'surface'; MenuText = 'text'; MenuHilight = 'selection'; MenuBar = 'surface'
    ActiveTitle = 'surfaceRaised'; TitleText = 'text'
    InactiveTitle = 'surface'; InactiveTitleText = 'muted'
    GradientActiveTitle = 'surfaceRaised'; GradientInactiveTitle = 'surface'
    WindowFrame = 'selection'; ActiveBorder = 'selection'; InactiveBorder = 'muted'
    AppWorkspace = 'background'; Scrollbar = 'surface'
    ButtonShadow = 'background'; ButtonDkShadow = 'background'
    ButtonHilight = 'accentSoft'; ButtonLight = 'surfaceRaised'; ButtonAlternateFace = 'surface'
    InfoText = 'text'; InfoWindow = 'surface'
  }
  $colors = foreach ($key in $roles.Keys) {
    $hex = $Theme.ui.($roles[$key])
    $rgb = (0, 2, 4 | ForEach-Object { [Convert]::ToInt32($hex.Substring(1 + $_, 2), 16) }) -join ' '
    [pscustomobject]@{ Key = $key; Role = "ui.$($roles[$key])"; Hex = $hex; Rgb = $rgb }
  }
  $marker = "; Generated by Meowsky Identity; id=$($Theme.id)"
  $lines = @($marker, '[Theme]', "DisplayName=$($Theme.name)", 'SetLogonBackground=0', '', '[Control Panel\Colors]')
  $lines += $colors | ForEach-Object { "$($_.Key)=$($_.Rgb)" }
  # Match the built-in Windows contrast theme visual style and selector.
  $lines += @('', '[Control Panel\Desktop]', 'Wallpaper=', 'TileWallpaper=0', 'WallpaperStyle=10',
    '', '[VisualStyles]', 'Path=%SystemRoot%\resources\themes\Aero\AeroLite.msstyles',
    'ColorStyle=NormalColor', 'Size=NormalSize', 'HighContrast=1',
    '', '[MasterThemeSelector]', 'MTSM=RJSPBS', '')
  [pscustomobject]@{
    Path = $path
    Content = $lines -join "`r`n"
    Marker = $marker
    Colors = @($colors)
    ManualStep = "Settings > Accessibility > Contrast themes > $($Theme.name) > Apply"
  }
}

function Install-MeowskyWindowsTheme {
  param($Theme)

  if ([Environment]::OSVersion.Platform -ne [PlatformID]::Win32NT) {
    throw 'The Windows contrast theme adapter requires Windows. Use --dry-run to inspect a plan.'
  }
  $definition = Get-MeowskyWindowsTheme -Theme $Theme
  $directory = Split-Path $definition.Path -Parent
  $temporaryPath = $null
  try {
    # Refuse redirected directories/files, and never replace a theme we do not own.
    $ancestor = $directory
    while ($ancestor) {
      if (Test-Path -LiteralPath $ancestor) {
        $item = Get-Item -LiteralPath $ancestor -Force -ErrorAction Stop
        if ($item.Attributes -band [IO.FileAttributes]::ReparsePoint) { throw "Refusing redirected theme directory: $ancestor" }
      }
      $ancestor = Split-Path $ancestor -Parent
    }
    $exists = Test-Path -LiteralPath $definition.Path
    if ($exists) {
      $item = Get-Item -LiteralPath $definition.Path -Force -ErrorAction Stop
      if ($item.PSIsContainer -or ($item.Attributes -band [IO.FileAttributes]::ReparsePoint)) {
        throw 'The destination is a directory or redirected file.'
      }
      $previous = [IO.File]::ReadAllText($definition.Path)
      if (-not $previous.StartsWith($definition.Marker + "`r`n")) {
        throw 'An unrelated theme already occupies this filename; it will not be overwritten.'
      }
      if ($previous -ceq $definition.Content) {
        return [pscustomobject]@{ Status = 'Unchanged'; Path = $definition.Path; ManualStep = $definition.ManualStep }
      }
    }
    [IO.Directory]::CreateDirectory($directory) | Out-Null
    $temporaryPath = Join-Path $directory ('.meowsky-' + [guid]::NewGuid().ToString('N') + '.tmp')
    [IO.File]::WriteAllText($temporaryPath, $definition.Content, [Text.Encoding]::Unicode)
    if ($exists) {
      if ([IO.File]::ReadAllText($definition.Path) -cne $previous) { throw 'The destination changed during installation; retry after inspecting it.' }
      # PowerShell 5.1 converts $null to an empty string for .NET string parameters.
      [IO.File]::Replace($temporaryPath, $definition.Path, [NullString]::Value)
    } else {
      [IO.File]::Move($temporaryPath, $definition.Path)
    }
    [pscustomobject]@{ Status = $(if ($exists) { 'Updated' } else { 'Installed' }); Path = $definition.Path; ManualStep = $definition.ManualStep }
  } catch {
    throw "Could not install Windows theme '$($definition.Path)': $($_.Exception.Message)"
  } finally {
    # Delete only our unique staging file in the checked theme directory.
    if ($temporaryPath -and [IO.File]::Exists($temporaryPath)) { [IO.File]::Delete($temporaryPath) }
  }
}
